### PR TITLE
STYLE: Replace VTK_OVERRIDE with override

### PR DESCRIPTION
**Pull request by jcfr**
This is required to support with VTK >= 8.90

### CODE REVIEW

**Comment by tashrifbillah** [comment]
In which platforms did you test it? Our primary interest is CentOS 7.

**Comment by jcfr** [comment]
These changes were tested on the following platforms:
* macOS 10.14 (with deployment target set to 10.13)
* Windows 10 + VS2019 + toolset v142 + x64
* Centos7: Slicer Linux build are done using `qt5-centos7` build environment, see https://github.com/Slicer/SlicerBuildEnvironment

**Comment by jcfr** [comment]
Waiting this is integrated, I will updated the extensions index to pull from my fork.

**Comment by tashrifbillah** [comment]
I can merge now if that is easier.

**Comment by jcfr** [comment]
> I can merge now if that would be easier for integration.

That would be great 🙏

**Pull request merged**
